### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by joaodlf** [go-ozzo/ozzo-validation#17]
Heya!

One of the latest updates has removed **validation.StructRules**, this effectively breaks CI tools like CircleCI. 

I love the package and use it quite a lot! But changes that effectively change the API without backwards compatibility make me worried :).

Just a heads up for future commits!

**Comment by qiangxue** [comment]
We follow semver when making new releases.

Because the latest change is breaking BC, we bumped up the version to be 3.0.

You can avoid the problem you mentioned by specifying explicitly which version (e.g. v2.1) your application depends on instead of depending on master. If you are using godep, glide, etc. to manage dependencies, you should be able to do so.

Thank you for using ozzo-validation!

**Comment by qiangxue** [comment]
Also, please refer to the release notes if you want to upgrade from 2.x to 3.x: https://github.com/go-ozzo/ozzo-validation/releases/tag/v3.0
